# Generated by Django 4.2.2 on 2023-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "sensor_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("varimax_path", models.CharField(max_length=500)),
                ("rfr_path", models.CharField(max_length=500)),
            ],
        ),
    ]
